image: archlinux
secrets:
  - 5fd6bbf1-8791-4c37-8e1f-2d423d1c6a12
packages:
  - docker
  - just
environment:
  GH_REPO: srht-solo-recreo
  GH_USER: rogeruiz
  SH_REPO: solo-recreo
  CI: true
tasks:
  - setup: |
      source ~/${SH_REPO}/ci/setup-docker.sh
  - test: |
      cd ~/"${SH_REPO}"
      just test bats
  - mirror-to-github: |
      cd ~/"${SH_REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${GH_REPO}"
