image: alpine/latest
secrets:
  - 5fd6bbf1-8791-4c37-8e1f-2d423d1c6a12
packages:
  - docker
  - containerd
environment:
  GH_REPO: srht-solo-recreo
  GH_USER: rogeruiz
  SH_REPO: solo-recreo
  JUST_VERSION: 1.39.0
tasks:
  - install-dependencies: |
      mkdir -p ~/bin
      wget -O - \
        https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz | \
      tar --directory ~/bin --extract --gzip --file - just
  - test: |
      export PATH="~/bin:$PATH"
      sudo dockerd
      cd ~/"${SH_REPO}"
      just test bats
  - mirror-to-github: |
      cd ~/"${SH_REPO}"
      git config --global credential.helper store
      git push --mirror "https://github.com/${GH_USER}/${GH_REPO}"
