# Flujo de trabajo pa' cerrar PR y Issue automáticamente :: Workflow for closing
# PR & Issue automatically.
# Public Domain (CC0) 2025 Roger Steve Ruiz
#
# This program is free software: you can redistribute it and/or modify it
# freely. It is in the public domain within the United States.
#
# The person who associated a work with this deed has dedicated the work to the
# public domain by waiving all of his or her rights to the work worldwide under
# copyright law, including all related and neighboring rights, to the extent
# allowed by law.
#
# You can copy, modify, distribute and perform the work, even for commercial
# purposes, all without asking permission.
#
# In no way are the patent or trademark rights of any person affected by CC0, nor
# are the rights that other persons may have in the work or in how the work is
# used, such as publicity or privacy rights.
#
# Unless expressly stated otherwise, the person who associated a work with this
# deed makes no warranties about the work, and disclaims liability for all uses of
# the work, to the fullest extent permitted by applicable law. When using or
# citing the work, you should not imply endorsement by the author or the affirmer.
#
# You should have received a copy of the CC0 1.0 Universal License along with
# this program. If not, see <https://creativecommons.org/publicdomain/zero/1.0/>.

name: 'Repo Lockdown'

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
  schedule:
    - cron: '20 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    name: Imponer clausura de'l repositorio
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          issue-comment: >
            Este repository **no acepta** propuestas través _GitHub_,
            mire al README pa' detalles sobre contribuyendo través _sourcehut_.

            ---

            This repository **does not accept** bug reports on _GitHub_,
            see the README for details about contributing via sourcehut.
          pr-comment: >
            Este repository **no acepta** solicitudes de cambios través _GitHub_,
            mire al README pa' detalles sobre contribuyendo través _sourcehut_.

            ---

            This repository **does not accept** pull requests on _ GitHub_,
            see the README for details about contributing via _sourcehut_.
